/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vankaitlynprogrammingckpt2;

import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.ListModel;

/**
 *
 * @author kaitlynvan
 */
public class PurchaseWindow extends javax.swing.JFrame {
    private BookStore kaitlynbookstore;
    ArrayList<Product> productList;
    private boolean enterMemberID = false;
    private boolean productIDs = false;
    private boolean paymentOp = false;

    /**
     * Creates new form PurchaseWindow
     */
    public PurchaseWindow() {
        initComponents();
    }
    public PurchaseWindow(BookStore kaitlynbookstore) {
        initComponents();
        this.kaitlynbookstore = kaitlynbookstore;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        purchasePID = new javax.swing.JLabel();
        inputPID = new javax.swing.JTextField();
        purchase = new javax.swing.JButton();
        questionMEM = new javax.swing.JLabel();
        inputMem = new javax.swing.JTextField();
        paymentOptions = new javax.swing.JComboBox<>();
        payment = new javax.swing.JLabel();
        leaveStore = new javax.swing.JButton();
        purchaseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        purchaseTitle.setText("Complete Purchase");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Product ID: 010, Quantity 5, Price: 5.99, \"Tweenty Moons\"\nProduct ID: 015, Quantity 5, Price: 13.99, \"Twilight\"\nProduct ID: 210, Quantity 10, Price: 11.99, \"Justice\", \"Justin Bieber\"\nProduct ID: 215, Quantity 12, Price: 14.24, \"Chilombo\", \"Jhene Aiko\"\nProduct ID: 310, Quantity 5, Price: 7.99, \"The Fault in Our Stars\nProduct ID: 315, Quantity 7, Price:  5.23, \"The Little Mermaid\");\n");
        jScrollPane1.setViewportView(jTextArea2);

        purchasePID.setText("Please enter the Product ID of the item you would like to purchase:");

        inputPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPIDActionPerformed(evt);
            }
        });

        purchase.setText("Purchase");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        questionMEM.setText("What is your member ID?");

        inputMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMemActionPerformed(evt);
            }
        });

        paymentOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Check ", "Paypal" }));
        paymentOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentOptionsActionPerformed(evt);
            }
        });

        payment.setText("Payment Method:");

        leaveStore.setText("Leave Store");
        leaveStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveStoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(purchaseTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(payment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(questionMEM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputMem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(purchasePID)
                                .addGap(18, 18, 18)
                                .addComponent(inputPID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(purchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leaveStore)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(purchaseLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(purchaseTitle)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchasePID)
                            .addComponent(inputPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(questionMEM)
                            .addComponent(inputMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paymentOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(purchaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchase)
                    .addComponent(leaveStore))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        // TODO add your handling code here:
        MainMenu myMainMenu = new MainMenu(kaitlynbookstore);
        myMainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_purchaseActionPerformed

    private void paymentOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentOptionsActionPerformed
        // TODO add your handling code here:
        paymentOp = true;
        if(enterMemberID && productIDs && paymentOp){
             purchase.setEnabled(true);
        }
    }//GEN-LAST:event_paymentOptionsActionPerformed

    private void inputPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPIDActionPerformed
        // TODO add your handling code here:
        productIDs = true;
        int productID = Integer.parseInt(inputPID.getText());
        kaitlynbookstore.buyProduct( productID);
        
        if(enterMemberID && productIDs && paymentOp){
            purchase.setEnabled(true);
        }
        
    }//GEN-LAST:event_inputPIDActionPerformed

    private void inputMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMemActionPerformed
        // TODO add your handling code here:
        enterMemberID = true;
        if(enterMemberID && productIDs && paymentOp){
            purchase.setEnabled(true);
        }
    }//GEN-LAST:event_inputMemActionPerformed

    private void leaveStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveStoreActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_leaveStoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputMem;
    private javax.swing.JTextField inputPID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton leaveStore;
    private javax.swing.JLabel payment;
    private javax.swing.JComboBox<String> paymentOptions;
    private javax.swing.JButton purchase;
    private javax.swing.JLabel purchaseLabel;
    private javax.swing.JLabel purchasePID;
    private javax.swing.JLabel purchaseTitle;
    private javax.swing.JLabel questionMEM;
    // End of variables declaration//GEN-END:variables
}
